// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "kuqoi",
  description: "Toolkit",
  subcommands: [
    {
      name: "create",
      description: "Create tools",
      subcommands: [
        {
          name: "cuid",
          description: "Create cuid",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "nanoid",
          description: "Create nanoid",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "uuid",
          description: "Create uuid",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "git",
      description: "Git tools",
      subcommands: [
        {
          name: "remote",
          description: "Git remote tools",
          options: [
            {
              name: ["-t", "--toggle"],
              description: "Toggle remote origin url",
            },
            { name: ["-g", "--get"], description: "Get remote origin url" },
            {
              name: ["-s", "--set"],
              description: "Set remote origin url",
              args: { name: "url" },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "npm",
      description: "Npm tools",
      subcommands: [
        {
          name: "sort",
          description: "Sort npm package.json",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "fix",
          description: "Fix tools",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "create",
          description: "Create tools",
          options: [
            {
              name: ["-r", "--registry"],
              description: "Set publish registry",
              args: { name: "registry" },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "mirrors",
          description: "Add the binary mirror URL of the library to ~/.npmrc",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "vscode",
      description: "Vscode tools",
      subcommands: [
        {
          name: "update",
          description: "Update vscode",
          subcommands: [
            {
              name: "extensions",
              description: "Update vscode extensions",
              options: [
                {
                  name: ["-h", "--help"],
                  description: "Display help for command",
                  priority: 49,
                },
              ],
            },
            {
              name: "help",
              description: "Display help for command",
              priority: 49,
              args: { name: "command", isOptional: true, template: "help" },
            },
          ],
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "vercel",
      description: "Vscode tools",
      subcommands: [
        {
          name: "clean",
          description: "Clean",
          options: [
            {
              name: ["-t", "--token"],
              description: "Vercel token",
              isRequired: true,
              args: { name: "token" },
            },
            {
              name: ["-a", "--app"],
              description: "Vercel app",
              isRequired: true,
              args: { name: "app" },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "shell",
      description: "Shell tools",
      subcommands: [
        {
          name: "alias",
          description: "Shell alias tools",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "help",
      description: "Display help for command",
      priority: 49,
      args: { name: "command", isOptional: true, template: "help" },
    },
  ],
  options: [
    { name: ["-V", "--version"], description: "Output the version number" },
    {
      name: ["-h", "--help"],
      description: "Display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
